온보딩 페이지 UI
YAPP-Github/24th-Web-Team-2-FE pull request #7
Opened 2024-07-08 14:43 UTC by moong23

## Why need this PR❓
온보딩 페이지 구현
https://jdustar1222.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?selectedIssue=SCRUM-56

## Changes ✌️
아직 백엔드 API가 완료되진 않아서 로직을 제외한 UI입니다.
- 관심사 페이지
`/onboard/interest`
<img width="1260" alt="image" src="https://github.com/YAPP-Github/24th-Web-Team-2-FE/assets/77270547/64f7479e-c2a3-45bc-967c-f3a7eb7fbee8">

- EmailList 페이지
`/onboard/emailList`
<img width="1260" alt="image" src="https://github.com/YAPP-Github/24th-Web-Team-2-FE/assets/77270547/8e5c5d40-6b72-4bd3-94db-ada62f1b2318">

2024-07-09 12:02 UTC, moong23 commented
일단 Interaction이 필요해서 'use client' 사용을 위해 분리한 코드를 page.tsx파일과 동일한 위치에 두었는데
해당 파일을 component/ 아래로 옮겨야 하는지에 대한 의견 주시면 반영하겠습니다 :)

2024-07-10 06:59 UTC, slinky-t requested changes
소소하게 리뷰 + 궁금한거 몇개 남겨봤습니당
확인 부탁드릴게요~!

2024-07-10 06:59 UTC, slinky-t commented on src/api/onboard.tsx
> +};
jsx 관련 코드가 전혀 없다보니 tsx보단 ts로 사용하는게 더 좋을 것 같습니당

2024-07-10 06:59 UTC, slinky-t commented on src/app/onboard/emailList/interaction.tsx
> +import { IncomingSenders } from '@/types/onboard';
import type으로 받아오는 방법도 있긴 합니다!
따로 정하지 않긴 해서 ㅎㅎ...
어떤게 좋을거같나요?

2024-07-10 06:59 UTC, slinky-t commented on src/app/onboard/emailList/page.tsx
> +const EmailList = async ({ userName = '채현' }: EmailListProps) => {
userName optional 아니다보니 default값 안넣어줘도 될듯요!?

2024-07-10 06:59 UTC, slinky-t commented on src/app/onboard/interest/page.tsx
> +  // const interestList = await getInterestList();
불필요한 주석들은 지워주시는게 좋을것같아요!

2024-07-10 06:59 UTC, slinky-t commented on src/network/index.tsx
> +      // Authorization: getCookie('userToken'),
클라에서 토큰 최대한 핸들링 안하고싶은데 어떻게 될지 모르겠네요 ㅎㅎ...😅

https://www.youtube.com/live/RQv86D0M5YY?si=SlIS954YtoaFzddI&t=4804
https://www.youtube.com/live/RQv86D0M5YY?si=3AIVIT5oJdcf-fNj&t=5467
https://cheatsheetseries.owasp.org/cheatsheets/HTML5_Security_Cheat_Sheet.html
<img width="624" alt="스크린샷 2024-07-07 오후 7 19 52" src="https://github.com/YAPP-Github/24th-Web-Team-2-FE/assets/164845145/29a1a9f7-d25d-4631-8e2a-a9f0477bfef6">

암호화가 아니라 인코딩된 식별자다보니 클라측 메모리에서 갖고있는건 좀 피하고싶어서... (백에서 csrf토큰 추가하는일 있더라도..)

httpOnly에 secure달린 쿠키 credentials헤더달아서 브라우저가 처리하게 하고싶긴 한데 백엔드랑 얘기가 어케될지 모르겠네요🥲

2024-07-10 06:59 UTC, slinky-t commented on src/app/onboard/emailList/page.tsx
> +import EmailListInteraction from './interaction';
절대경로 안들어갔어요! + 밑에 더있어용

2024-07-10 06:59 UTC, slinky-t commented on src/assets/icons/ServiceIcon.tsx
> +        strokeWidth='0.15'
어떤 이슈가 있었나요!?

2024-07-10 06:59 UTC, slinky-t commented on src/api/onboard.tsx
> +  console.log('get interest', data.data);
콘솔 지워도 될거같아요!

2024-07-10 06:59 UTC, slinky-t commented on src/app/onboard/emailList/interaction.tsx
> +import { IncomingSenders } from '@/types/onboard';
네이밍이 딱 읽었을 때 타입같은 느낌이 부족한 것 같은데, 어떻게 생각하시나요!?

2024-07-10 06:59 UTC, slinky-t commented on src/app/onboard/emailList/page.tsx
> +  const incomingSenders2 = await getIncomingSenders2();
일단 목데이터라서 네이밍을 1 2로 지은건가요!?

2024-07-10 06:59 UTC, slinky-t commented on src/app/onboard/emailList/page.tsx
> +const getIncomingSenders = async () => {
목데이터라서 이후에 api 호출 코드 들어갈거라서 async로 미리 선언해둔건가요!?

2024-07-10 06:59 UTC, slinky-t commented on src/app/onboard/interest/page.tsx
> +async function getInterest() {
위에서 const로 선언했었는데, 여기서는 function키워드라서 그런데, 통일하는게 좋을 것 같아서요! 
어떤게 더 좋나요?

2024-07-10 07:08 UTC, dladncks1217 requested changes
> 일단 Interaction이 필요해서 'use client' 사용을 위해 분리한 코드를 page.tsx파일과 동일한 위치에 두었는데 해당 파일을 component/ 아래로 옮겨야 하는지에 대한 의견 주시면 반영하겠습니다 :)

저는 component하위로 옮기는게 좋을 것 같긴 합니다!

---

소소하게 리뷰 + 궁금한거 몇개 남겨봤습니당
확인 부탁드릴게요~!

2024-07-10 07:08 UTC, dladncks1217 commented on src/api/onboard.tsx
> +  console.log('get interest', data.data);
콘솔 지워도 될거같아요!

2024-07-10 07:08 UTC, dladncks1217 commented on src/api/onboard.tsx
> +};
jsx 관련 코드가 전혀 없다보니 tsx보단 ts로 사용하는게 더 좋을 것 같습니당

2024-07-10 07:08 UTC, dladncks1217 commented on src/app/onboard/emailList/interaction.tsx
> +import { IncomingSenders } from '@/types/onboard';
import type으로 받아오는 방법도 있긴 합니다!
따로 정하지 않긴 해서 ㅎㅎ...
어떤게 좋을거같나요?

2024-07-10 07:08 UTC, dladncks1217 commented on src/app/onboard/emailList/interaction.tsx
> +import { IncomingSenders } from '@/types/onboard';
네이밍이 딱 읽었을 때 타입같은 느낌이 부족한 것 같은데, 어떻게 생각하시나요!?

2024-07-10 07:08 UTC, dladncks1217 commented on src/app/onboard/emailList/page.tsx
> +import EmailListInteraction from './interaction';
절대경로 안들어갔어요! + 밑에 더있어용

2024-07-10 07:08 UTC, dladncks1217 commented on src/app/onboard/emailList/page.tsx
> +const EmailList = async ({ userName = '채현' }: EmailListProps) => {
userName optional 아니다보니 default값 안넣어줘도 될듯요!?

2024-07-10 07:08 UTC, dladncks1217 commented on src/app/onboard/emailList/page.tsx
> +  const incomingSenders2 = await getIncomingSenders2();
일단 목데이터라서 네이밍을 1 2로 지은건가요!?

2024-07-10 07:08 UTC, dladncks1217 commented on src/app/onboard/emailList/page.tsx
> +const getIncomingSenders = async () => {
목데이터라서 이후에 api 호출 코드 들어갈거라서 async로 미리 선언해둔건가요!?

2024-07-10 07:08 UTC, dladncks1217 commented on src/app/onboard/interest/page.tsx
> +async function getInterest() {
위에서 const로 선언했었는데, 여기서는 function키워드라서 그런데, 통일하는게 좋을 것 같아서요!
어떤게 더 좋나요?

2024-07-10 07:08 UTC, dladncks1217 commented on src/app/onboard/interest/page.tsx
> +  // const interestList = await getInterestList();
불필요한 주석들은 지워주시는게 좋을것같아요!

2024-07-10 07:08 UTC, dladncks1217 commented on src/assets/icons/ServiceIcon.tsx
> +        strokeWidth='0.15'
어떤 이슈가 있었나요!?

2024-07-10 07:08 UTC, dladncks1217 commented on src/network/index.tsx
> +      // Authorization: getCookie('userToken'),
클라에서 토큰 최대한 핸들링 안하고싶은데 어떻게 될지 모르겠네요 ㅎㅎ...😅

https://www.youtube.com/live/RQv86D0M5YY?si=SlIS954YtoaFzddI&t=4804
https://www.youtube.com/live/RQv86D0M5YY?si=3AIVIT5oJdcf-fNj&t=5467
https://cheatsheetseries.owasp.org/cheatsheets/HTML5_Security_Cheat_Sheet.html
<img width="624" alt="스크린샷 2024-07-07 오후 7 19 52" src="https://github.com/YAPP-Github/24th-Web-Team-2-FE/assets/164845145/29a1a9f7-d25d-4631-8e2a-a9f0477bfef6">

암호화가 아니라 인코딩된 식별자다보니 클라측 메모리에서 갖고있는건 좀 피하고싶어서... (백에서 csrf토큰 추가하는일 있더라도..)

httpOnly에 secure달린 쿠키 credentials헤더달아서 브라우저가 처리하게 하고싶긴 한데 백엔드랑 얘기가 어케될지 모르겠네요🥲

2024-07-10 13:29 UTC, moong23 commented on src/api/onboard.tsx
> +};
`onboard.tsx` -> `onboard.ts` 수정해놓을게요!

2024-07-10 13:29 UTC, moong23 commented on src/app/onboard/emailList/interaction.tsx
> +import { IncomingSenders } from '@/types/onboard';
좋아요 👍 type관련 부분은 import type으로 불러오도록 할게요 :)

2024-07-10 13:29 UTC, moong23 commented on src/app/onboard/emailList/page.tsx
> +const EmailList = async ({ userName = '채현' }: EmailListProps) => {
이 부분이 원래는 api를 통해 userData를 받아와야하는 부분인데, api의 연결 이슈로 인해 일단 UI를 보여주기 위해 넣어놓았어요! API 연결하면서 해당 부분을 수정하도록 할게요!

2024-07-10 13:29 UTC, moong23 commented on src/assets/icons/ServiceIcon.tsx
> +        strokeWidth='0.15'
react에서는 kebab case가 아닌 camel case로 (stroke-width가 아닌 strokeWidth로) 써야하는것으로 알고있어요! 
![image](https://github.com/YAPP-Github/24th-Web-Team-2-FE/assets/77270547/5983aae1-48b7-44e6-be52-c0e2919eb65f)

2024-07-10 13:29 UTC, moong23 commented on src/app/onboard/emailList/page.tsx
> +  const incomingSenders2 = await getIncomingSenders2();
맞습니다 :) 해당 부분은 api 연결하면서 모두 싹다 바뀔것같아서 일단 data holding용입니다

2024-07-10 13:29 UTC, moong23 commented on src/app/onboard/emailList/page.tsx
> +const getIncomingSenders = async () => {
넵 요기도 실제 api연결하려고 했다가 백엔드 배포가 아직 안됐다는걸 깨닫고 함수 body만 갈아끼웠어서 async만 남아있는것 같네요!
이 부분도 실제 api로 갈아끼우는 과정에서 다 바뀔것 같습니다~!

2024-07-10 13:29 UTC, moong23 commented on src/app/onboard/interest/page.tsx
> +async function getInterest() {
엇 요기 왜 async function으로 되어있을까요...
const로 통일하는것 괜찮을까요? 저는 arrow function 문법을 더 선호합니다

2024-07-10 13:29 UTC, moong23 commented on src/network/index.tsx
> +      // Authorization: getCookie('userToken'),
**~백엔드 해줘~**

2024-07-10 13:40 UTC, moong23 commented
늦은 시간에 시간에 쫓겨서 작업하다보니 부족한 부분이 조금 많은 것 같네요 :(
조금 더 정신 차리고 작업해보겠습니다 ㅎㅎ

2024-07-10 13:58 UTC, dladncks1217 commented on src/assets/icons/ServiceIcon.tsx
> +        strokeWidth='0.15'
아 생각해보니 svg였군요?
제가 시간날때 한번 래핑해서 쓰기 편하게 만들어볼게용

2024-07-10 14:00 UTC, dladncks1217 commented
고생하셨습니다~!

2024-07-10 14:00 UTC, dladncks1217 approved these changes

2024-07-10 14:18 UTC, merged